<a href="https://colab.research.google.com/github/VijayaBhargavi198/5731Assignments/blob/master/In_class_exercise_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The third In-class-exercise (9/16/2020, 20 points in total)

The purpose of this exercise is to under users' information needs, then collect the data for analysis.

Question 1 (8 points): Describe an interesting research question (or practical question) you have in mind, what kind of data should be collected to answer the question(s)? How many data needed for the analysis? The detail steps for collecting and save the data.

In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

Research question:
Current topic thats everywhere is corona, so i intend to work on corona updates website and I intend to scrape the website and get details about the countries and their current corona virus infections and deaths and effects of corona on each country.
Data is collected from the website https://www.worldometers.info/coronavirus/ , it  is currently the most updated website on corona data.

How much data needed for the analysis?
My idea of analysis is to scrape data from this website and get information about every country thatâ€™s effected and later analysis could go on the grounds as to which country is most effected and what are the common causes that could have increased the spread in the countries etc. 
For now, The considered data has every country as the row and gives details like new cases, new deaths, total number of cases, total number of deaths and ratio of cases, ratio of deaths and population etc.

The detail steps for collecting and save the data.
1.	Actually, we try to understand the website as the first step.see what data we have, if tables are used in the website then what rows and columns we have.
2.  once thats done, we should import the required libraries.
3.	Use beautiful soup and read the page,'User-Agent':'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7',was used to surpass restrictions.
4.	Every web item would have tags,we should understand and identify which tag is corresponding to which item of the website.
5.	Try to call and extract data using these identified tags.
6.	Now once we identify and call the data, it is good to display but cannot be stored, for storing we used data frames. we need to store all the extracted data into data frames (pandas was used)
7.	Displaying data as per required using the data frames.

Question 2 (12 points): Write python code to collect 500 items of the data you plan to collect above.

In [ ]:
# You code here (Please add comments in the code):

import pandas as pd
from bs4 import BeautifulSoup
import urllib
import requests

In [ ]:
page = urllib.request.urlopen(urllib.request.Request("https://www.worldometers.info/coronavirus/",None,{'User-Agent':'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7',}))

soup = BeautifulSoup(page)
# print(soup.prettify)

In [ ]:
data_table = soup.find_all("tr",{"style":""})
number = soup.find_all("td",{"style":"font-size:12px;color: grey;text-align:center;vertical-align:middle;"})
country = soup.find_all("a",{"class":"mt_a"})
# total_cases = soup.find_all("td",{"style":"font-weight: bold; font-size:15px; text-align:left;"})
newCases = soup.find_all("td",{"style":"font-weight: bold; text-align:right;background-color:#FFEEAA;"})
totalDeaths = soup.find_all("td",{"style":"font-weight: bold; text-align:right;"})
newDeaths = soup.find_all("td",{"style":"font-weight: bold; \n                                    text-align:right;background-color:red; color:white"})
list_of_values = soup.find_all("td",{"style":"font-weight: bold; text-align:right"})
#print(list_of_values)
activeCases = soup.find_all("td",{"style":"text-align:right;font-weight:bold;"})
values = list()

In [ ]:
#-------------------------------------------------

numbers_l = list()
country_names =list()
total_recovered = list()
serious_or_critical = list()
tot_cases_1mpop = list()
deaths_1Mpop = list()
total_tests = list()
tests_1Mpop = list()
population=list()
total_cases = list()
new_cases = list()
total_deaths = list()
new_deaths =list()
active_cases = list()
for i in list_of_values:
  values.append(i.text)

for i in range(0,len(values),8):
  total_cases.append(values[i])
  total_recovered.append(values[i+1])
  serious_or_critical.append(values[i+2])
  tot_cases_1mpop.append(values[i+3])
  deaths_1Mpop.append(values[i+4])
  total_tests.append(values[i+5])
  tests_1Mpop.append(values[i+6])
  population.append(values[i+7])


for i,c,n,t,nd,ac in zip(number,country,newCases,totalDeaths,newDeaths,activeCases):
  numbers_l.append(i.text)
  country_names.append(c.text)
  new_cases.append(n.text)
  total_deaths.append(t.text)
  new_deaths.append(nd.text)
  active_cases.append(ac.text)

ouputDF = pd.DataFrame(list(zip(country_names,total_cases,new_cases,total_deaths,new_deaths,total_recovered,active_cases,serious_or_critical,tot_cases_1mpop,deaths_1Mpop,total_tests,tests_1Mpop,population)),\
                       columns = ['country','total_cases','new_cases','total_deaths','new_deaths','total_recovered','active_cases','serious_or_critical','total_cases_1m_Population','Deaths_For_1M_population','Total_Tests','Tests_for_1M_Population','Population'])

pd.set_option("display.max_rows", 500, "display.max_columns", 50) 
ouputDF

,country,total_cases,new_cases,total_deaths,new_deaths,total_recovered,active_cases,serious_or_critical,total_cases_1m_Population,Deaths_For_1M_population,Total_Tests,Tests_for_1M_Population,Population
0,USA,"6,918,702","+44,106","203,071",+858,"4,182,723","2,532,908","14,258","20,876",613,"96,183,552","290,216","331,420,450"
1,India,"5,305,475","+92,789","85,625","+1,221","4,205,201","1,014,649","8,944","3,836",62,"61,572,343","44,524","1,382,900,689"
2,Brazil,"4,495,183","+37,740","135,793",+762,"3,789,139","570,251","8,318","21,116",638,"14,617,980","68,666","212,883,816"
3,Russia,"1,091,186","+5,905","19,195",+134,"901,207","170,784","2,300","7,477",132,"42,000,000","287,774","145,948,080"
4,Colombia,"750,471","+6,526","23,850",+185,"621,521","105,100",863,"14,716",468,"3,332,152","65,338","50,998,462"
5,Peru,"750,098","+3,182",,+201,"594,513","124,439","1,439","22,683",942,"3,614,738","109,309","33,069,039"
6,Mexico,"684,113","+4,697","31,146",+90,"488,416","123,518","2,557","5,294",559,"1,549,643","11,992","129,221,511"
7,Spain,"659,334","+2,055",,+85,N/A,N/A,"1,345","14,101",652,"10,756,835","230,050","46,758,719"
8,South Africa,"657,627","+1,677","72,179",+31,"586,844","54,926",539,"11,059",267,"4,003,590","67,324","59,467,369"
9,Argentina,"601,713","+13,215","30,495",+57,"467,286","121,936","3,108","13,287",276,"1,682,249","37,149","45,284,429"
10,Chile,"442,827","+3,049",N/A,+154,"415,981","14,647",902,"23,123",637,"2,975,891","155,388","19,151,322"
11,France,"428,696","+4,322","15,857",+144,"91,574","305,873",827,"6,565",479,"10,000,000","153,128","65,304,832"
12,Iran,"416,198","+1,541",,+27,"355,505","36,741","3,869","4,942",284,"3,691,399","43,830","84,220,988"
13,UK,"385,936",+576,"12,491",+22,N/A,N/A,127,"5,679",614,"21,368,297","314,411","67,962,867"
14,Bangladesh,"345,805","+4,305","12,199",+31,"252,335","88,589",,"2,095",30,"1,796,509","10,885","165,039,541"
15,Saudi Arabia,"328,720",+752,"31,249",+76,"308,352","15,938","1,189","9,411",127,"5,966,884","170,833","34,928,178"
16,Iraq,"311,690","+1,771","23,952",+9,"245,305","57,977",536,"7,713",208,"2,021,586","50,027","40,409,852"
17,Pakistan,"304,386","+1,907","41,732",+62,"291,683","6,295",579,"1,372",29,"3,090,660","13,935","221,788,860"
18,Turkey,"299,810","+3,257",N/A,+10,"264,805","27,628","1,402","3,547",87,"9,076,278","107,370","84,532,416"
19,Italy,"294,932","+2,202","4,881",+47,"216,807","42,457",208,"4,880",590,"10,246,163","169,519","60,442,405"
20,Philippines,"279,526","+3,891","4,430",+7,"208,790","65,906","1,048","2,544",44,"3,293,210","29,968","109,890,105"
21,Germany,"271,244","+3,815","8,408",+114,"241,300","20,480",246,"3,235",113,"14,557,136","173,626","83,841,923"
22,Indonesia,"236,519","+3,228","6,408",+27,"170,774","56,409",,863,34,"2,841,352","10,365","274,140,070"
23,Israel,"179,071",+699,"7,377",+68,"130,024","47,851",581,"19,469",130,"2,931,763","318,753","9,197,590"
24,Ukraine,"169,472",+547,"35,668",+1,"75,486","90,518",177,"3,880",79,"1,925,482","44,086","43,675,866"
25,Canada,"141,566",+224,"4,830",+33,"123,512","8,853",76,"3,744",243,"6,422,063","169,838","37,812,954"
26,Bolivia,"129,419","+1,527","9,464",+1,"87,716","34,192",71,"11,055",642,"282,838","24,160","11,706,734"
27,Qatar,"122,917",+78,,+48,"119,822","2,886",59,"43,777",74,"714,183","254,356","2,807,805"
28,Ecuador,"122,257",+596,"9,336",+12,"97,063","14,165",375,"6,907",623,"370,864","20,953","17,699,585"
29,Romania,"110,217",+131,"1,196",+18,"88,235","17,622",447,"5,738",227,"2,185,923","113,795","19,209,377"
30,Kazakhstan,"107,134",+704,"3,468",+5,"101,610","3,853",221,"5,691",89,"2,733,455","145,208","18,824,434"
31,Dominican Republic,"106,732","+2,028","9,201",+1,"80,179","24,519",210,"9,818",187,"422,070","38,825","10,871,122"
32,Panama,"104,138","+2,760","7,511",+41,"77,881","24,044",152,"24,055",511,"417,620","96,468","4,329,082"
33,Egypt,"101,772","+1,974",209,+7,"87,958","8,081",41,991,56,"135,000","1,314","102,738,349"
34,Kuwait,"98,528",+680,,+5,"88,776","9,172",101,"23,000",135,"701,484","163,749","4,283,910"
35,Belgium,"97,976",+865,"11,029",+40,"18,854","69,186",74,"8,446",857,"2,768,761","238,676","11,600,514"
36,Morocco,"97,264",+485,,+1,"76,690","18,819",264,"2,629",47,"2,342,307","63,300","37,003,550"
37,Oman,"91,753",+757,"4,360",+9,"84,648","6,287",180,"17,874",159,"309,212","60,235","5,133,398"
38,Netherlands,"90,047",+243,"1,671",+17,N/A,N/A,65,"5,253",366,"2,042,887","119,167","17,143,094"
39,Sweden,"88,237",+460,"2,034",+2,N/A,N/A,15,"8,725",580,"1,393,161","137,762","10,112,810"
40,Guatemala,"84,344",+602,,+20,"73,748","7,520",5,"4,690",171,"286,730","15,943","17,984,983"
41,UAE,"83,433",+780,"2,213",+12,"72,790","10,240",,"8,414",41,"8,562,443","863,516","9,915,789"
42,Japan,"77,494",+690,,+6,"69,899","6,113",170,613,12,"1,811,516","14,333","126,391,624"
43,Poland,"77,328","+1,556","5,733",+3,"63,312","11,746",83,"2,044",60,"3,081,867","81,450","37,837,563"
44,Belarus,"75,230","+2,020",580,+20,"73,098","1,359",,"7,962",82,"1,700,790","180,004","9,448,646"
45,Honduras,"70,120",+11,"9,936",+7,"20,677","47,321",20,"7,056",214,"165,904","16,694","9,937,794"
46,Ethiopia,"67,515",+626,"1,755",+6,"27,638","38,805",289,584,9,"1,184,473","10,251","115,551,504"
47,Portugal,"67,176",+219,,+5,"45,053","20,229",57,"6,592",186,"2,345,680","230,190","10,190,196"
48,Venezuela,"64,284",+488,818,+3,"52,564","11,200",146,"2,262",18,"1,864,663","65,615","28,418,294"
49,Bahrain,"63,879",+239,,+1,"56,700","6,959",43,"37,280",128,"1,313,471","766,545","1,713,495"
50,Costa Rica,"62,374",+46,"6,273",+1,"23,160","38,528",245,"12,220",134,"193,045","37,822","5,104,063"
51,Nepal,"61,593",+665,N/A,+16,"43,820","17,383",,"2,106",13,"894,373","30,580","29,246,701"
52,Singapore,"57,543",+91,,+5,"57,071",445,,"9,819",5,"2,498,073","426,277","5,860,205"
53,Nigeria,"56,735","+1,073","5,865",+1,"48,092","7,550",7,274,5,"482,321","2,328","207,194,373"
54,Uzbekistan,"50,253",+117,N/A,+1,"46,527","3,307",243,"1,497",12,"1,377,915","41,044","33,571,712"
55,Algeria,"49,413",+11,"3,076",+4,"34,818","12,936",31,"1,123",38,,,"44,017,064"
56,Switzerland,"49,283",+148,403,+5,"40,500","6,738",29,"5,685",236,"1,251,614","144,391","8,668,205"
57,Armenia,"46,910",+808,"1,482",+6,"42,369","3,615",,"15,824",312,"255,927","86,332","2,964,445"
58,Ghana,"45,760",+558,"2,270",+1,"44,973",492,6,"1,466",9,"464,420","14,881","31,208,065"
59,Moldova,"45,648",+62,773,+3,"33,734","10,728",549,"11,322",294,"246,764","61,203","4,031,912"
60,Kyrgyzstan,"45,244",+248,"2,122",+18,"41,415","2,766",24,"6,911",162,"267,718","40,893","6,546,842"
61,Czechia,"45,228",+750,"1,072",+3,"23,652","21,082",91,"4,222",46,"1,148,880","107,239","10,713,292"
62,Azerbaijan,"38,894",+97,"1,894",+5,"36,424","1,898",,"3,829",56,"1,041,184","102,492","10,158,720"
63,Afghanistan,"38,883",+48,,+13,"32,576","4,870",93,994,37,"107,968","2,761","39,110,298"
64,Kenya,"36,724",+616,520,+5,"23,709","12,369",44,680,12,"504,988","9,349","54,017,393"
65,Austria,"36,661",+292,,+5,"28,451","7,447",62,"4,066",85,"1,413,965","156,803","9,017,463"
66,Palestine,"34,401",+126,220,+1,"23,333","10,818",,"6,711",49,"359,873","70,206","5,125,985"
67,Serbia,"32,757",+454,686,+4,"31,411",607,20,"3,752",85,"1,063,667","121,845","8,729,645"
68,Ireland,"32,271",+68,390,+8,"23,364","7,115",14,"6,520",362,"1,030,817","208,266","4,949,527"
69,Paraguay,"31,113",+42,27,+6,"16,313","14,216",137,"4,351",82,"241,837","33,818","7,151,143"
70,Lebanon,"27,518",+189,,+1,"10,739","16,498",121,"4,036",41,"700,966","102,800","6,818,729"
71,El Salvador,"27,346",+143,"1,093",+2,"20,825","5,717",93,"4,211",124,"359,765","55,406","6,493,262"
72,Australia,"26,861",+941,,+1,"23,855","2,169",15,"1,051",33,"7,224,163","282,604","25,562,804"
73,Libya,"26,438",+46,419,+6,"14,207","11,813",,"3,837",61,"176,378","25,595","6,891,077"
74,Bosnia and Herzegovina,"24,897",+338,"1,659",+3,"17,365","6,780",,"7,599",230,"220,278","67,233","3,276,320"
75,S. Korea,"22,783",+27,"2,045",+1,"19,771","2,635",150,444,7,"2,206,365","43,027","51,278,779"
76,Denmark,"21,847",+234,926,+6,"17,110","4,102",3,"3,769",110,"3,246,363","560,045","5,796,614"
77,Cameroon,"20,371",+94,295,+1,"19,124",831,30,763,16,"149,000","5,584","26,682,247"
78,Ivory Coast,"19,200",+64,"1,186",+1,"18,392",688,,724,5,"148,957","5,618","26,513,133"
79,Bulgaria,"18,733",+125,"1,063",+1,"13,510","4,470",34,"2,700",109,"488,865","70,473","6,936,886"
80,North Macedonia,"16,417",+14,494,+1,"13,732","2,002",4,"7,880",328,"172,700","82,895","2,083,355"
81,Hungary,"16,111",+77,572,+1,"4,240","11,202",29,"1,669",69,"591,618","61,276","9,654,982"
82,Madagascar,"15,971",+129,"1,437",+1,"14,587","1,167",30,574,8,"66,460","2,387","27,837,665"
83,Greece,"14,738",+95,646,+2,"3,804","10,607",71,"1,416",31,"1,181,712","113,497","10,411,859"
84,Senegal,"14,645",+36,763,+1,"11,051","3,293",29,870,18,"163,965","9,740","16,834,684"
85,Croatia,"14,513",+45,250,+2,"12,169","2,100",21,"3,540",60,"249,023","60,742","4,099,687"
86,Zambia,"14,022",+59,739,+10,"13,207",486,,758,18,"137,017","7,411","18,489,439"
87,Sudan,"13,535",+44,,+3,"6,759","5,940",,307,19,,,"44,061,334"
88,Norway,"12,708",+177,"1,792",+4,"10,371","2,070",2,"2,340",49,"928,024","170,896","5,430,329"
89,Albania,"12,073",+14,,+3,"6,831","4,889",18,"4,196",123,"73,651","25,599","2,877,111"
90,DRC,"10,456",+103,,+3,"9,863",325,,116,3,,,"90,116,049"
91,Guinea,"10,231",+235,584,+1,"9,660",508,24,775,5,"30,764","2,330","13,205,931"
92,Namibia,"10,207",+5,,+2,"7,947","2,152",14,"4,002",42,"86,092","33,754","2,550,552"
93,Malaysia,"10,147",+214,281,+879,"9,264",754,11,313,4,"1,417,154","43,667","32,453,958"
94,French Guiana,"9,659",+4,804,"+1,174","9,298",296,4,"32,167",216,"62,400","207,809","300,276"
95,Maldives,"9,494",+24,837,+857,"8,033","1,428",12,"17,499",61,"135,958","250,594","542,542"
96,Tajikistan,"9,259",+78,418,+144,"8,026","1,160",,966,8,,,"9,582,111"
97,Finland,"8,858",+71,752,+95,"7,700",819,3,"1,598",61,"866,092","156,261","5,542,589"
98,Gabon,"8,678",+3,377,+187,"7,827",798,5,"3,880",24,"143,996","64,381","2,236,606"
99,Haiti,"8,600",+18,635,+300,"6,363","2,016",,752,19,"25,752","2,253","11,432,052"
100,Tunisia,"8,570",+424,416,+67,"2,342","6,095",47,724,11,"179,035","15,115","11,844,983"
101,Luxembourg,"7,718",+213,120,+162,"6,703",891,1,"12,287",197,"771,950","1,228,981","628,122"
102,Zimbabwe,"7,647",+137,753,+344,"5,883","1,540",,513,15,"157,144","10,540","14,908,642"
103,Montenegro,"7,503",+59,683,+84,"4,892","2,482",,"11,946",205,"60,011","95,546","628,083"
104,Mauritania,"7,346",+40,669,+50,"6,865",320,3,"1,571",34,"77,298","16,535","4,674,801"
105,Mozambique,"6,264",+217,217,+176,"3,502","2,722",,199,1,"121,398","3,862","31,434,838"
106,Slovakia,"6,256",+61,327,+21,"3,390","2,827",22,"1,146",7,"403,055","73,817","5,460,217"
107,Malawi,"5,716",+7,,+36,"4,026","1,511",4,297,9,"49,798","2,589","19,231,751"
108,Uganda,"5,594",+78,301,+30,"2,544","2,989",,122,1,"444,346","9,652","46,034,419"
109,Djibouti,"5,403",+5,244,+84,"5,333",9,,"5,452",62,"73,695","74,362","991,036"
110,Eswatini,"5,215",+95,329,+6,"4,478",634,11,"4,485",89,"31,766","27,320","1,162,725"
111,Cabo Verde,"5,141",+182,,+66,"4,548",543,,"9,225",90,"76,576","137,412","557,273"
112,Cuba,"5,004",+25,836,+13,"4,249",644,19,442,10,"524,374","46,302","11,325,108"
113,Equatorial Guinea,"5,002",+36,,+51,"4,509",410,,"3,542",59,"57,119","40,443","1,412,318"
114,Hong Kong,"4,997",+39,267,+8,"4,696",198,13,665,14,"2,783,134","370,590","7,510,012"
115,Nicaragua,"4,961",+10,,+122,"2,913","1,901",,747,22,,,"6,641,305"
116,Congo,"4,934",+24,353,+8,"3,887",959,,890,16,,,"5,546,138"
117,CAR,"4,782",+20,268,+60,"1,830","2,890",2,987,13,"31,677","6,535","4,847,400"
118,Suriname,"4,671",+75,63,+7,"4,160",416,7,"7,947",162,"12,462","21,203","587,756"
119,Rwanda,"4,671",+2,108,+31,"2,845","1,801",,359,2,"471,767","36,238","13,018,502"
120,Myanmar,"4,467",+30,129,+33,"1,130","3,267",,82,1,"212,826","3,906","54,488,177"
121,Jamaica,"4,374",+22,65,+27,"1,225","3,098",8,"1,476",17,"70,077","23,643","2,963,958"
122,Jordan,"4,344",+31,,+13,"2,511","1,804",13,425,3,"1,045,700","102,271","10,224,752"
123,Slovenia,"4,195",+7,33,+15,"2,939","1,116",11,"2,018",67,"196,338","94,439","2,079,000"
124,Angola,"3,848",+81,,+19,"1,443","2,258",16,116,4,"65,951","1,994","33,074,172"
125,Syria,"3,731",+4,73,+4,918,"2,645",,212,10,,,"17,588,527"
126,Trinidad and Tobago,"3,651",+1,339,+5,"1,586","2,005",6,"2,607",43,"28,774","20,546","1,400,469"
127,Lithuania,"3,565",+32,,+28,"2,181","1,297",,"1,314",32,"716,972","264,195","2,713,795"
128,Mayotte,"3,541",+2,,+13,"2,964",537,2,"12,915",146,"13,000","47,415","274,176"
129,Thailand,"3,497",+1,53,+6,"3,328",111,1,50,0.8,"749,213","10,728","69,837,937"
130,Gambia,"3,473",+4,,+27,"1,951","1,415",,"1,429",44,"14,554","5,988","2,430,575"
131,Aruba,"3,460",+8,221,+12,"2,128","1,309",11,"32,378",215,"27,760","259,769","106,864"
132,Guadeloupe,"3,426",+1,,+16,837,"2,563",28,"8,562",65,"38,505","96,229","400,139"
133,Somalia,"3,390",+3,133,+4,"2,812",480,,212,6,,,"15,984,091"
134,Sri Lanka,"3,281",+6,,+15,"3,060",208,,153,0.6,"262,378","12,242","21,432,641"
135,RÃ©union,"3,194",+18,124,+15,"1,794","1,385",,"3,562",17,"35,419","39,500","896,684"
136,Bahamas,"3,177",+5,224,+10,"1,626","1,482",65,"8,062",175,"16,386","41,584","394,047"
137,Georgia,"3,119",+4,,+9,"1,435","1,665",,782,5,"529,121","132,695","3,987,493"
138,Mali,"2,991",+32,129,+1,"2,332",531,,147,6,"46,993","2,307","20,370,108"
139,Estonia,"2,814",+9,,+17,"2,357",393,3,"2,121",48,"182,635","137,658","1,326,729"
140,Malta,"2,634","+46,295",,+4,"1,996",621,2,"5,962",38,"226,330","512,293","441,798"
141,South Sudan,"2,609","+96,793",161,+2,"1,290","1,270",,232,4,"12,044","1,073","11,221,627"
142,Botswana,"2,567","+35,757",,+6,624,"1,930",1,"1,087",6,"156,054","66,082","2,361,534"
143,Benin,"2,280","+5,762",40,+9,"1,950",290,,187,3,"169,063","13,871","12,188,538"
144,Guinea-Bissau,"2,275","+5,698",39,+3,"1,127","1,109",5,"1,150",20,,,"1,977,629"
145,Iceland,"2,230","+7,568",179,+2,"2,112",108,,"6,526",29,"244,348","715,055","341,719"
146,Sierra Leone,"2,153","+4,444",61,+11,"1,649",432,,269,9,,,"8,010,819"
147,Guyana,"2,102","+2,128",61,+7,"1,314",726,16,"2,670",79,"11,771","14,950","787,371"
148,Yemen,"2,024","+4,541",,+2,"1,221",218,,68,20,,,"29,962,452"
149,Uruguay,"1,876","+12,701",103,+5,"1,582",248,,540,13,"208,293","59,917","3,476,334"
150,New Zealand,"1,809","+1,863",50,+1,"1,714",70,4,362,5,"897,077","179,340","5,002,100"
151,Burkina Faso,"1,797","+10,593",111,+2,"1,173",568,,85,3,,,"21,020,871"
152,Togo,"1,640","+2,815",,+1,"1,251",348,,197,5,"81,514","9,799","8,318,907"
153,Belize,"1,567","+3,395",83,+18,742,806,3,"3,926",48,"12,182","30,521","399,141"
154,Cyprus,"1,565","+1,593",,+5,"1,282",261,2,"1,294",18,"344,831","285,162","1,209,245"
155,Andorra,"1,564",+593,103,+8,"1,164",347,4,"20,235",686,"137,457","1,778,412","77,292"
156,Latvia,"1,498","+4,326",,+4,"1,248",214,,796,19,"290,907","154,610","1,881,559"
157,Liberia,"1,334",+545,147,+11,"1,214",38,,262,16,,,"5,082,296"
158,Lesotho,"1,327","+1,648",,+11,687,607,,618,15,"17,261","8,044","2,145,889"
159,Niger,"1,183","+1,585",,+5,"1,104",10,,49,3,"19,794",812,"24,382,599"
160,Chad,"1,147","+3,355",88,+1,966,100,,69,5,,,"16,522,273"
161,Martinique,"1,122","+2,177",,+10,98,"1,006",5,"2,990",48,"19,534","52,063","375,202"
162,French Polynesia,"1,099","+3,635",,+7,672,425,3,"3,907",7,"18,802","66,850","281,258"
163,Vietnam,"1,068","+4,791",62,+1,941,92,,11,0.4,"1,009,145","10,347","97,525,870"
164,Sao Tome and Principe,908,"+3,584",,+9,873,20,,"4,127",68,"4,523","20,558","220,011"
165,San Marino,723,"+1,120",,+1,663,18,3,"21,299","1,237","7,470","220,055","33,946"
166,Turks and Caicos,712,+586,95,+9,651,48,4,,,,,
167,Channel Islands,663,+244,,+2,565,93,3,"17,075",129,"2,990","77,006","38,828"
168,Sint Maarten,644,+732,25,+1,575,21,2,"3,697",276,"117,227","672,922","174,206"
169,Papua New Guinea,565,"+1,679",70,+4,477,69,6,"13,146",442,"2,720","63,285","42,980"
170,Tanzania,516,+72,,+4,232,278,,57,0.7,"17,276","1,923","8,982,487"
171,Taiwan,509,+615,51,+3,183,305,7,8,0.3,,,"60,082,410"
172,Burundi,503,+672,,+1,478,18,,21,0.3,"91,110","3,824","23,826,131"
173,Comoros,473,+141,29,+1,374,98,,40,0.08,"27,836","2,327","11,963,031"
174,Faeroe Islands,470,+825,140,+2,449,14,,538,8,,,"873,456"
175,Mauritius,430,"+1,153",147,+2,412,18,,"8,793",,"113,394","2,318,753","48,903"
176,Eritrea,366,"+2,488",168,+1,338,18,,288,8,"239,204","188,020","1,272,226"
177,Gibraltar,364,+557,60,+5,305,59,,102,,,,"3,556,809"
178,Isle of Man,346,+224,87,+1,315,31,,"10,270",,"41,870","1,242,839","33,689"
179,Saint Martin,339,"+1,753",,+20,312,3,,"3,982",282,"11,469","134,723","85,130"
180,Mongolia,330,+740,40,+1,206,118,11,"8,504",155,"2,968","76,485","38,805"
181,Cambodia,311,+786,,+2,302,9,1,95,,"64,166","19,507","3,289,407"
182,Bhutan,275,+561,58,+2,274,1,,16,,"121,530","7,248","16,767,934"
183,CuraÃ§ao,252,+837,,+1,182,70,,326,,"122,546","158,448","773,417"
184,Cayman Islands,228,+224,107,+2,83,144,1,"1,388",6,"1,080","6,576","164,238"
185,Monaco,208,"+1,040",,+2,204,3,,"3,157",15,"37,425","568,027","65,886"
186,Barbados,191,+689,23,+2,152,38,1,"4,860",25,"51,953","1,321,892","39,302"
187,Bermuda,185,+770,,+1,172,6,,644,24,"21,069","73,296","287,451"
188,Brunei,178,+868,26,+1,164,5,,"2,860",145,"56,728","911,615","62,228"
189,Seychelles,145,+705,,+1,141,1,,331,7,"55,434","126,454","438,374"
190,Liechtenstein,141,"+1,302",,"+1,012",136,5,,"1,432",,"5,200","52,804","98,478"
191,Antigua and Barbuda,112,"+1,246",98,"+1,139",108,3,,"2,936",26,900,"23,590","38,152"
192,British Virgin Islands,95,+18,,+967,92,0,,968,31,"2,332","23,771","98,103"
193,St. Vincent Grenadines,69,+131,13,+132,48,20,2,"2,279",33,"4,410","145,670","30,274"
194,Macao,64,+612,15,+124,64,0,,576,,"4,603","41,462","111,016"
195,Caribbean Netherlands,46,+228,,+190,46,0,,71,,"4,238","6,508","651,209"
196,Fiji,36,+530,,+629,17,18,,"1,370",38,"1,516","57,697","26,275"
197,Saint Lucia,32,+295,69,+64,26,4,1,36,2,"9,570","10,659","897,839"
198,Timor-Leste,27,+59,,+239,26,1,,147,,"7,547","41,059","183,808"
199,New Caledonia,27,+81,19,+264,26,1,,20,,"5,146","3,888","1,323,698"
200,Dominica,26,+622,128,+18,26,0,,91,,"13,463","47,060","286,084"
201,Grenada,24,"+3,123",64,+179,18,6,,333,,"2,077","28,837","72,025"
202,Laos,24,+17,17,+46,24,0,,213,,"6,252","55,506","112,636"
203,St. Barth,23,+119,49,+20,22,1,,3,,"46,070","6,313","7,297,871"
204,Saint Kitts and Nevis,23,+183,,+21,16,7,,"2,327",,"2,075","209,935","9,884"
205,Greenland,17,+780,,+31,17,0,,319,,"2,138","40,128","53,280"
206,Montserrat,14,+837,13,+4,14,0,,247,,"7,421","130,672","56,791"
207,Falkland Islands,13,+82,,+82,12,0,,"2,604",200,373,"74,705","4,993"
208,Vatican City,13,+224,,+63,13,0,,"3,713",,"2,261","645,815","3,501"
209,Saint Pierre Miquelon,12,+694,40,+12,12,0,,"14,981",,,,801
210,Western Sahara,11,+86,,+69,5,6,,"1,900",,"1,051","181,583","5,788"
211,Anguilla,10,+34,,+4,8,1,,17,2,,,"600,372"
212,China,9,+685,39,+135,,7,,,,,,
213,China,3,+886,,+14,3,0,,200,,"1,020","67,855","15,032"
214,USA,"85,255",+394,10,+76,"80,456",165,3,59,3,"160,000,000","111,163","1,439,323,776"
215,India,"85,223",+153,,+5,"80,448",141,2,59,3,"160,000,000","111,163","1,439,323,776"
216,Brazil,"6,874,596",+453,72,+53,"4,155,039","2,517,344","14,227","20,743",610,"95,235,022","287,354","331,420,450"
217,Russia,"5,212,686",+26,62,+33,"4,109,828","1,018,454","8,944","3,769",61,"60,565,728","43,796","1,382,900,689"
218,Peru,"4,457,443",+154,585,+49,"3,753,082","569,330","8,318","20,938",634,"14,617,980","68,666","212,883,816"
219,Colombia,"1,085,281",+186,,+11,"895,868","170,352","2,300","7,436",131,"41,748,928","286,053","145,948,080"
220,Mexico,"750,098",+54,,+11,"594,513","124,439","1,439","22,683",942,"3,614,738","109,309","33,069,039"
221,South Africa,"743,945",+710,46,+17,"615,457","104,823",863,"14,588",464,"3,298,415","64,677","50,998,462"